version: "3.1"

networks:
  net1:

services:
  db:
    image: postgres:14.1
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: app
      POSTGRES_DB: person
    ports:
      - "5432:5432"
    networks:
      net1:
        aliases:
          - database
